# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: './'
      verbose: true
    displayName: "Install dependencies"
  - script: |
      git config --global user.email "build-ado@springworks.in"
      git config --global user.name "Azure DevOps Build"
      npm version patch -m "Bump version to %s [skip ci]" --force
    displayName: "Bump release version"
  - script: |
      git push origin HEAD:$(Build.SourceBranchName)
    displayName: "Updated version in code"
  - task: Npm@1
    inputs:
      command: 'publish'
      workingDir: './'
      verbose: true
      publishRegistry: 'useFeed'
      publishFeed: 'cad167df-8d9c-44fe-8127-6d49aca56571'
    displayName: "Publish pacakge"
